### ISSUE TITLE
pandoc-types-1.17.3.1 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [jgm/pandoc-types#37]
The error is:

~~~
Text/Pandoc/Definition.hs:97:10: error:
    • No instance for (Semigroup Pandoc)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Pandoc’
   |
97 | instance Monoid Pandoc where
   |          ^^^^^^^^^^^^^

Text/Pandoc/Definition.hs:106:10: error:
    • No instance for (Semigroup Meta)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Meta’
    |
106 | instance Monoid Meta where
    |          ^^^^^^^^^^^
~~~~

**Comment by jgm** [comment]
I think this is fixed in 1.17.4.
However, I couldn't compile the tests due to problems
with some of the dependencies.

**Comment by peti** [comment]
The new version compiles fine. Thank you very much for the update!
